controller:
  resources:
    limits:
      memory: 1Gi
      cpu: 500m
    requests:
      memory: 512Mi
      cpu: 500m
# We need to use the VPC DNS resolver as CoreDNS will not be available in
# a brand new cluster without any nodes.
dnsPolicy: Default
