{{- if .Values.al2023.enabled }}
---
apiVersion: karpenter.k8s.aws/v1
kind: EC2NodeClass
metadata:
  name: al2023
spec:
  amiFamily: AL2023
  amiSelectorTerms:
    - alias: al2023@v20251007
  blockDeviceMappings:
    {{- range $deviceName, $config := index .Values.blockDeviceMappings "al2023" }}
    - deviceName: {{ $deviceName | quote }}
      ebs:
        deleteOnTermination: {{ default true $config.deleteOnTermination }}
        volumeSize: {{ $config.volumeSize }}
        volumeType: {{ default "gp3" $config.volumeType }}
    {{- end }}
  kubelet:
    maxPods: 110
  metadataOptions:
    httpEndpoint: enabled
    httpProtocolIPv6: disabled
    httpPutResponseHopLimit: 2 # This is changed to enable IMDS access from containers not on the host network
    httpTokens: required
  {{- if .Values.al2023UserData }}
  userData: |-
{{ .Values.al2023UserData | indent 4 }}
  {{- end }}
  role: eks-node
  securityGroupSelectorTerms:
    - tags:
        karpenter.sh/discovery: {{ .Values.clusterName }}
  subnetSelectorTerms:
    - tags:
        karpenter.sh/discovery: {{ .Values.clusterName }}
{{- end }}

{{- if .Values.bottlerocket.enabled }}
---
apiVersion: karpenter.k8s.aws/v1
kind: EC2NodeClass
metadata:
  name: bottlerocket
spec:
  amiFamily: Bottlerocket
  amiSelectorTerms:
    - alias: bottlerocket@latest
  blockDeviceMappings:
    {{- range $deviceName, $config := index .Values.blockDeviceMappings "bottlerocket" }}
    - deviceName: {{ $deviceName | quote }}
      ebs:
        deleteOnTermination: {{ default true $config.deleteOnTermination }}
        volumeSize: {{ $config.volumeSize }}
        volumeType: {{ default "gp3" $config.volumeType }}
    {{- end }}
  kubelet:
    maxPods: 110
  metadataOptions:
    httpEndpoint: enabled
    httpProtocolIPv6: disabled
    httpPutResponseHopLimit: 2 # This is changed to enable IMDS access from containers not on the host network
    httpTokens: required
  {{- if .Values.bottlerocketUserData }}
  userData: |-
{{ .Values.bottlerocketUserData | indent 4 }}
  {{- end }}
  role: eks-node
  securityGroupSelectorTerms:
    - tags:
        karpenter.sh/discovery: {{ .Values.clusterName }}
  subnetSelectorTerms:
    - tags:
        karpenter.sh/discovery: {{ .Values.clusterName }}
{{- end }}
