{{- if .Values.al2023.enabled }}
---
apiVersion: karpenter.sh/v1
kind: NodePool
metadata:
  labels:
    karpenter.sh/nodepool: al2023
  name: al2023
spec:
  weight: {{ .Values.nodePoolWeight.al2023 }}
  disruption:
    consolidateAfter: 30s
    consolidationPolicy: WhenEmptyOrUnderutilized
  template:
    spec:
      expireAfter: {{ .Values.expireAfter }}
      nodeClassRef:
        group: karpenter.k8s.aws
        kind: EC2NodeClass
        name: al2023
      kubelet:
        # High threshold for Garbage Collection (GC) to prevent disk pressure (eviction usually starts at 85%)
        imageGCHighThresholdPercent: {{ .Values.imageGCHighThresholdPercent }}
        # Low threshold for GC to ensure ample space for new images
        imageGCLowThresholdPercent: {{ .Values.imageGCLowThresholdPercent }}
      {{- if .Values.al2023.topologySpreadConstraints }}
      topologySpreadConstraints:
        {{- toYaml .Values.al2023.topologySpreadConstraints | nindent 8 }}
      {{- end }}
      requirements:
        - key: "karpenter.k8s.aws/instance-hypervisor"
          operator: In
          values: ["nitro"]
        - key: kubernetes.io/arch
          operator: In
          values:
          {{- range .Values.allowedArch }}
            - {{ . }}
          {{- end }}
        - key: kubernetes.io/os
          operator: In
          values: ["linux"]
        - key: karpenter.sh/capacity-type
          operator: In
          values: ["on-demand", "spot"]
        - key: karpenter.k8s.aws/instance-category
          operator: In
          values: ["c", "g", "m", "r"]
        - key: karpenter.k8s.aws/instance-generation
          operator: Gt
          values: ["2"]
        {{- if .Values.al2023.extraRequirements }}
        {{- toYaml .Values.al2023.extraRequirements | nindent 8 }}
        {{- end }}
{{- end }}

{{- if .Values.bottlerocket.enabled }}
---
apiVersion: karpenter.sh/v1
kind: NodePool
metadata:
  labels:
    karpenter.sh/nodepool: bottlerocket
  name: bottlerocket
spec:
  weight: {{ .Values.nodePoolWeight.bottlerocket }}
  disruption:
    consolidateAfter: 30s
    consolidationPolicy: WhenEmptyOrUnderutilized
  template:
    spec:
      expireAfter: {{ .Values.expireAfter }}
      kubelet:
        # High threshold for Garbage Collection (GC) to prevent disk pressure (eviction usually starts at 85%)
        imageGCHighThresholdPercent: {{ .Values.imageGCHighThresholdPercent }}
        # Low threshold for GC to ensure ample space for new images
        imageGCLowThresholdPercent: {{ .Values.imageGCLowThresholdPercent }}
      nodeClassRef:
        group: karpenter.k8s.aws
        kind: EC2NodeClass
        name: bottlerocket
      {{- if .Values.bottlerocket.topologySpreadConstraints }}
      topologySpreadConstraints:
        {{- toYaml .Values.bottlerocket.topologySpreadConstraints | nindent 8 }}
      {{- end }}
      requirements:
        - key: "karpenter.k8s.aws/instance-hypervisor"
          operator: In
          values: ["nitro"]
        - key: kubernetes.io/arch
          operator: In
          values:
          {{- range .Values.allowedArch }}
            - {{ . }}
          {{- end }}
        - key: kubernetes.io/os
          operator: In
          values: ["linux"]
        - key: karpenter.sh/capacity-type
          operator: In
          values: ["on-demand", "spot"]
        - key: karpenter.k8s.aws/instance-category
          operator: In
          values: ["c", "g", "m", "r"]
        - key: karpenter.k8s.aws/instance-generation
          operator: Gt
          values: ["2"]
        {{- if .Values.bottlerocket.extraRequirements }}
        {{- toYaml .Values.bottlerocket.extraRequirements | nindent 8 }}
        {{- end }}
{{- end }}

---
{{- if .Values.hlb.enabled }}
apiVersion: karpenter.sh/v1
kind: NodePool
metadata:
  name: hlb-ami-86
spec:
  replicas: {{ .Values.replicas }}
  disruption:
    consolidateAfter: 30s
    consolidationPolicy: WhenEmptyOrUnderutilized
  template:
    spec:
      expireAfter: {{ .Values.expireAfter }}
      nodeClassRef:
        group: karpenter.k8s.aws
        kind: EC2NodeClass
        name: hlb-ami-x86
      kubelet:
        # High threshold for Garbage Collection (GC) to prevent disk pressure (eviction usually starts at 85%)
        imageGCHighThresholdPercent: {{ .Values.imageGCHighThresholdPercent }}
        # Low threshold for GC to ensure ample space for new images
        imageGCLowThresholdPercent: {{ .Values.imageGCLowThresholdPercent }}
      requirements:
        - key: "karpenter.k8s.aws/instance-hypervisor"
          operator: In
          values: ["nitro"]
        - key: kubernetes.io/arch
          operator: In
          values:
          {{- range .Values.allowedArch }}
            - {{ . }}
          {{- end }}
        - key: kubernetes.io/os
          operator: In
          values: ["linux"]
        - key: karpenter.sh/capacity-type
          operator: In
          values: ["on-demand", "spot"]
        - key: karpenter.k8s.aws/instance-category
          operator: In
          values: ["c", "m", "r"]
        - key: karpenter.k8s.aws/instance-generation
          operator: Gt
          values: ["2"]
      startupTaints:
        - key: node-role.kubernetes.io/hlb
          effect: NoSchedule
{{- end }}
