---
apiVersion: karpenter.sh/v1
kind: NodePool
metadata:
  name: al2023
spec:
  template:
    spec:
      requirements:
        - key: "karpenter.k8s.aws/instance-hypervisor"
          operator: In
          values: ["nitro"]
        - key: kubernetes.io/arch
          operator: In
          values: ["amd64"]
        - key: kubernetes.io/os
          operator: In
          values: ["linux"]
        - key: karpenter.sh/capacity-type
          operator: In
          values: ["on-demand", "spot"]
        - key: karpenter.k8s.aws/instance-category
          operator: In
          values: ["c", "m", "r"]
        - key: karpenter.k8s.aws/instance-generation
          operator: Gt
          values: ["2"]
      expireAfter: {{ .Values.expireAfter }}
      nodeClassRef:
        group: karpenter.k8s.aws
        kind: EC2NodeClass
        name: al2023
      kubelet:
        # High threshold for Garbage Collection (GC) to prevent disk pressure (eviction usually starts at 85%)
        imageGCHighThresholdPercent: {{ .Values.imageGCHighThresholdPercent }}
        # Low threshold for GC to ensure ample space for new images
        imageGCLowThresholdPercent: {{ .Values.imageGCLowThresholdPercent }}
  limits:
    cpu: 100
    memory: 256Gi
  disruption:
    consolidationPolicy: WhenEmptyOrUnderutilized
    consolidateAfter: 30s
---
apiVersion: karpenter.sh/v1
kind: NodePool
metadata:
  name: bottlerocket
spec:
  template:
    spec:
      requirements:
        - key: "karpenter.k8s.aws/instance-hypervisor"
          operator: In
          values: ["nitro"]
        - key: kubernetes.io/arch
          operator: In
          values: ["amd64"]
        - key: kubernetes.io/os
          operator: In
          values: ["linux"]
        - key: karpenter.sh/capacity-type
          operator: In
          values: ["on-demand", "spot"]
        - key: karpenter.k8s.aws/instance-category
          operator: In
          values: ["c", "m", "r"]
        - key: karpenter.k8s.aws/instance-generation
          operator: Gt
          values: ["2"]
      expireAfter: {{ .Values.expireAfter }}
      nodeClassRef:
        group: karpenter.k8s.aws
        kind: EC2NodeClass
        name: bottlerocket
      kubelet:
        # Trigger Garbage Collection at 70% to prevent disk pressure (eviction usually starts at 85%)
        imageGCHighThresholdPercent: {{ .Values.imageGCHighThresholdPercent }}
        # Target 50% usage after GC to ensure ample space for new images
        imageGCLowThresholdPercent: {{ .Values.imageGCLowThresholdPercent }}
  limits:
    cpu: 100
    memory: 256Gi
  disruption:
    consolidationPolicy: WhenEmptyOrUnderutilized
    consolidateAfter: 30s
