{{- range .Values.nodePools }}
---
apiVersion: karpenter.sh/v1
kind: NodePool
metadata:
  name: {{ .name }}
  labels:
    karpenter.sh/nodepool: {{ .name }}
spec:
  template:
    spec:
      nodeClassRef:
        group: karpenter.k8s.aws
        kind: EC2NodeClass
        name: {{ .node_class_ref }}
      requirements:
        {{- range .requirements }}
        - key: {{ .key | quote }}
          operator: {{ .operator }}
          values:
          {{- range .values }}
            - {{ . | quote }}
          {{- end }}
        {{- end }}
      {{- with .kubelet }}
      kubelet:
        {{- if .image_gc_high_threshold_percent }}
        imageGCHighThresholdPercent: {{ .image_gc_high_threshold_percent }}
        {{- end }}
        {{- if .image_gc_low_threshold_percent }}
        imageGCLowThresholdPercent: {{ .image_gc_low_threshold_percent }}
        {{- end }}
      {{- end }}
      {{- with .startup_taints }}
      startupTaints:
        {{- toYaml . | nindent 8 }}
      {{- end }}
  {{- with .disruption }}
  disruption:
    consolidationPolicy: {{ .consolidation_policy | default "WhenEmptyOrUnderutilized" }}
    consolidateAfter: {{ .consolidate_after | default "30s" }}
    expireAfter: {{ .expire_after | default "720h" }}
  {{- end }}
  {{- with .limits }}
  limits:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- if .weight }}
  weight: {{ .weight }}
  {{- end }}
{{- end }}
