---
apiVersion: vpcresources.k8s.aws/v1beta1
kind: SecurityGroupPolicy
metadata:
  name: karpenter
spec:
  podSelector:
    matchLabels:
      app.kubernetes.io/name: karpenter
  securityGroups:
    groupIds:
      - {{ .Values.nodeSecurityGroupId }}
