---
allowedArch:
  - amd64
blockDeviceMappings:
  al2023:
    /dev/xvda:
      volumeSize: 40Gi
      volumeType: gp3
  bottlerocket:
    /dev/xvda:
      volumeSize: 8Gi
      volumeType: gp3
    /dev/xvdb:
      volumeSize: 40Gi
      volumeType: gp3
